spring:
  application:
    name: notification-service
  #  cloud:
  #    config:
  #      uri: ${SPRING_CLOUD_CONFIG_URI}
  datasource:
    url: jdbc:h2:mem:notification_db_test
    driver-class-name: org.h2.Driver
    username: root
    password:
    driverClassName: org.h2.Driver
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: guest
    password: guest

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

  h2:
    console:
      path=/h2-console:
      enabled: true

  # Mail configuration for email notifications
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Disable cloud config for tests
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

textbee:
  api:
    key: ${TEXTBEE_API_KEY:d0067ec4-9b8a-49c4-9295-e8120c19a162}
  device:
    id: ${TEXTBEE_DEVICE_ID:68f1c11d6a418a16ec8f483e}

# Email settings
app:
  email:
    from-name: FortressBank

logging:
  level:
    com.uit.accountservice: DEBUG
    org.springframework.security: DEBUG
