networks:
  internal:
    driver: bridge
    name: fortressbank-network

volumes:
  userdb_data:
  redis_data:
  referencedb_data:
  transactiondb_data:
  accountdb_data:
  keycloak_db_data:
  notificationdb_data:
