server:
  port: ${SERVER_PORT:4002}

spring:
  application:
    name: transaction-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/transactiondb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

services:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:4001}
    timeout: 5000 # 5 seconds timeout for sync calls

# JWT Configuration
jwt:
  issuer-uri: ${JWT_ISSUER_URI:http://localhost:8888/realms/fortressbank-realm}

# Eureka Configuration
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.uit.transactionservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
